import { readText } from "../util/fs.js";

/**
 * Generic JSON-tree route extractor, used to seed the route catalogue once from whatever route
 * table a project happens to have (a menu config, a permission tree, a webmap the user supplies).
 *
 * Deliberately field-driven and depth-agnostic: real menu trees are ragged (the same tree can put
 * one screen three levels deep and another four), carry unnamed grouping nodes, and repeat the
 * same path under several top-level sections. None of that is special-cased.
 *
 * This is a one-off import on purpose. The source file is typically generated by the project's own
 * backend and changes without warning, so it must never become something the tool reads at query
 * time — the catalogue itself is the durable artefact.
 */

export interface ImportOptions {
  /** field holding the route path (default "path") */
  pathField?: string;
  /** field holding the human name (default "name") */
  nameField?: string;
  /** field holding child nodes (default "children") */
  childrenField?: string;
}

export interface ImportedRoute {
  path: string;
  name?: string;
  /** names of the ancestors that had one, outermost first */
  chain: string[];
}

type Node = Record<string, unknown>;

function isNode(v: unknown): v is Node {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function str(v: unknown): string | undefined {
  return typeof v === "string" && v.trim().length > 0 ? v.trim() : undefined;
}

export function extractRoutes(root: unknown, opts: ImportOptions = {}): ImportedRoute[] {
  const pathField = opts.pathField ?? "path";
  const nameField = opts.nameField ?? "name";
  const childrenField = opts.childrenField ?? "children";
  const out: ImportedRoute[] = [];

  const walk = (value: unknown, chain: string[]): void => {
    if (Array.isArray(value)) {
      for (const item of value) walk(item, chain);
      return;
    }
    if (!isNode(value)) return;

    const name = str(value[nameField]);
    const path = str(value[pathField]);
    // A node's own name belongs to its children's chain, never to its own placement.
    if (path) out.push({ path, ...(name ? { name } : {}), chain: [...chain] });
    walk(value[childrenField], name ? [...chain, name] : chain);
  };

  walk(root, []);
  return out;
}

/** Read a JSON file tolerating a UTF-8 BOM (exports from Windows tooling routinely carry one). */
export function readJsonTree(file: string): unknown {
  const text = readText(file).replace(/^﻿/, "");
  return JSON.parse(text) as unknown;
}

export interface ImportSummary {
  entries: number;
  uniquePaths: number;
  named: number;
}

export function summarise(routes: ImportedRoute[]): ImportSummary {
  return {
    entries: routes.length,
    uniquePaths: new Set(routes.map((r) => r.path.toLowerCase())).size,
    named: routes.filter((r) => r.name).length,
  };
}
